### ISSUE TITLE
Annotation process

### ISSUE THREAD

**Issue by Caro-Ca** [JanaSperschneider/EffectorP-1.0#1]
Hi!
Is there an option to annotate the output of this software? First I got gene models from FunGAP. Then with SignalP I found the sequences that got the signal peptide and this output was the input for EffectorP. However, I need to annotate the candidate effectors to gain more information about their name, family name, function, etc. 

Thank you in advance for your help.

**Comment by JanaSperschneider** [comment]
Hi,

you can do sequence similarity searches with your predicted effectors, e.g. using Blast or phmmer or InterProScan. It is likely that your effector candidates will mostly be hypothetical proteins with no similarity to characterized other proteins.

Cheers,
Jana
